### ISSUE TITLE
Readme example doesn't seem to work (golang 1.8)

### ISSUE THREAD

**Issue by dkrieger** [SierraSoftworks/multicast#1]
When I run the example in the readme using the golang:1.8 docker image, the only output I get is "Listener 2: Hello World!" Is the example flawed, does this require a newer version of golang, or is the package broken?

**Comment by notheotherben** [comment]
Hi there @dkrieger,

Sorry for the confusion there. The library does indeed work, however for the sake of simplicity and brevity, that example lacks any coordination of the subscriptions to ensure that there are no race conditions. 

Here's the verbose example which does pass as you would expect it to:

```go
package main

import (
	"fmt"
	"sync"

	"github.com/SierraSoftworks/multicast"
)

func main() {
	c := multicast.New()
	wg := sync.WaitGroup{}

	wg.Add(2)

	go func() {
		defer wg.Done()
		l := c.Listen()
		wg.Done()
		for msg := range l.C {
			fmt.Printf("Listener 1: %s\n", msg)
		}
		fmt.Println("Listener 1 Closed")
	}()

	go func() {
		defer wg.Done()
		l := c.Listen()
		wg.Done()
		for msg := range l.C {
			fmt.Printf("Listener 2: %s\n", msg)
		}
		fmt.Println("Listener 2 Closed")
	}()

	wg.Wait()
	wg.Add(2)
	c.C <- "Hello World!"
	c.Close()

	wg.Wait()
}
```

You'll notice that I've used a `sync.WaitGroup` to prevent the initial emission of `c.C <- "Hello World"` until after we've subscribed with both listeners and then again to ensure that all listeners have a chance to close and print their output before we exit the application.

What you're seeing is simply a case of the second goroutine (Listener 2) having subscribed and received the message before the first gorouting (Listener 1) has had a chance to subscribe itself.

I've also updated the examples to show this and validate their behaviour a bit better, but if this doesn't clear things up then please do let me know and I'd be happy to go into further detail.
